language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

services:
  - mysql

addons:
  postgresql: "9.3"

before_script:
  - mysql -e 'create database sabredav'
#  - composer self-update
  - composer install --prefer-source
#  - echo "zend.enable_gc=0" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - psql -c 'create database sabredav;' -U postgres

script:
  - ./bin/phpunit --configuration tests/phpunit.xml
  - ./bin/phpcs  -p --standard=tests/phpcs/ruleset.xml lib/

notifications:
  irc:
    channels:
        - "chat.freenode.net#sabredav"
    on_success: change
    on_failure: change
