language: php
php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - SABRE_MYSQLUSER="root"
    - SABRE_MYSQLPASS=""
    - SABRE_MYSQLDSN="mysql:host=127.0.0.1;dbname=sabredav_test"
  matrix:
    - LOWEST_DEPS="" TEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest" TEST_DEPS="tests/Sabre/"

services:
  - mysql
  - postgresql


sudo: false

before_script:
#  - mysql -u root -h 127.0.0.1 sabredav_test -e 'SELECT VERSION();'
#- mysql -u root -h 127.0.0.1 -e 'create database sabredav_test'
  - psql -c "create database sabredav_test" -U postgres
  - psql -c "create user sabredav with PASSWORD 'sabredav';GRANT ALL PRIVILEGES ON DATABASE sabredav_test TO sabredav" -U postgres
  - composer update --prefer-dist $LOWEST_DEPS

# Required for postgres 9.5
dist: trusty

addons:
   postgresql: "9.5"

script:
  - ./bin/phpunit --verbose --configuration tests/phpunit.xml.dist $TEST_DEPS
  - ./bin/sabre-cs-fixer fix . --dry-run --diff

cache:
  directories:
    - $HOME/.composer/cache
