version: '3.4'
services:
  pgsql:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    tmpfs:
      - /var/lib/postgresql/data
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    tmpfs:
      - /var/lib/mysql
  phpunit:
    depends_on:
      - mysql
      - pgsql
    environment:
      SABRE_MYSQLUSER: root
      SABRE_MYSQLPASS: secret
      SABRE_MYSQLDSN: mysql:host=mysql;dbname=test
      SABRE_PGSQLDSN: pgsql:host=pgsql;dbname=test;user=root;password=secret
    image: phpunit/phpunit
    tty: true
    working_dir: /project
    entrypoint: [
      "bin/phpunit",
      "-c",
      "tests/phpunit.xml.dist"
    ]
    volumes:
      - ./:/project